"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Place = { id: string; name: string; category: string; address: string; distanceM: number };
export function KakaoRestaurantAddForm() {
  const router = useRouter(); const [query, setQuery] = useState(""); const [places, setPlaces] = useState<Place[]>([]); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function search() { setBusy(true); setMessage(null); const res = await fetch(`/api/admin/restaurants/search-kakao?q=${encodeURIComponent(query)}`); const data = await res.json(); setPlaces(data.places ?? []); setMessage(data.message ?? (data.places?.length ? null : "2km 이내 Kakao 검색 결과가 없어요.")); setBusy(false); }
  async function add(placeId: string) { setBusy(true); const res = await fetch("/api/admin/restaurants/search-kakao", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query, placeId }) }); const data = await res.json(); if (!res.ok) setMessage(data.message ?? "등록에 실패했습니다."); else { setMessage(data.existing ? "이미 등록된 식당이에요." : "식당을 등록했어요."); router.refresh(); } setBusy(false); }
  return <section className="rounded-card bg-surface p-4 shadow-card"><p className="font-semibold text-brand-dark">Kakao 상호명 추가</p><div className="mt-3 flex gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="예: 복만당" className="flex-1 rounded-control border border-line px-3 py-2"/><button type="button" onClick={search} disabled={!query.trim() || busy} className="rounded-control bg-brand px-3 py-2 font-semibold text-black">검색</button></div>{message && <p className="mt-2 text-sm text-ink-muted">{message}</p>}<ul className="mt-3 flex flex-col gap-2">{places.map((place) => <li key={place.id} className="rounded-control bg-surface-muted p-3"><p className="font-semibold">{place.name} · {place.distanceM}m</p><p className="text-sm text-ink-muted">{place.category} · {place.address}</p><button type="button" onClick={() => add(place.id)} disabled={busy} className="mt-2 text-sm font-semibold text-brand-dark">이 식당 추가</button></li>)}</ul></section>;
}
